name: test

on: [push, pull_requests]

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Fetch latest release version
        id: fetch-latest-release
        uses: ./

      - name: Test
        run: echo ${{ steps.fetch-latest-release.outputs.latest-release }}